### ISSUE TITLE
Installer of the plugin is succesfull but zwavejs2mqtt fails to run.

### ISSUE THREAD

**Issue by RoelandvanD** [tprelog/iocage-zwavejs2mqtt#1]
Hi, 

After running the installer for this iocage package, the jail is succesfully started and the settings menu is visible, but zwavejs2mqtt fails to start or become available for the webapplication.
`
Select: 5
Starting zwavejs2mqtt.
zwavejs2mqtt is not running.`

The problems occured after updating. It persisted after deleting the plugin completly and reinstalling it.

I've attachted the install notes below! Unfortunatly, the reffered logs files are not more specific on this. Hope this can still be usefull for you!
I am using 12.2-RELEASE-p8.

_Install Notes:

plugin_initialized: -> 2.20210320

plugin_version: -> 2.20210320

zwavejs2mqtt_app_dir: -> /usr/local/share/zwavejs2mqtt

zwavejs2mqtt_store_dir: -> /usr/local/etc/zwavejs2mqtt

Downloading latest release... OK

OK

npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

OK

npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.

OK

npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.

OK

npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

OK

npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.

OK

npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

OK

npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

OK

npm WARN deprecated eslint-loader@4.0.2: This loader has been deprecated. Please use eslint-webpack-plugin

OK

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

OK

npm WARN deprecated har-validator@5.1.5: this library is no longer supported

OK

npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> @serialport/bindings@9.2.0 install /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d/node_modules/@serialport/bindings

> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> @serialport/bindings@9.2.0 install /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d/node_modules/@serialport/bindings

> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=x64 libc= platform=freebsd)

gmake: Entering directory '/tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d/node_modules/@serialport/bindings/build'

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=x64 libc= platform=freebsd)

CXX(target) Release/obj.target/bindings/src/serialport.o

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=x64 libc= platform=freebsd)

CXX(target) Release/obj.target/bindings/src/serialport_unix.o

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=x64 libc= platform=freebsd)

CXX(target) Release/obj.target/bindings/src/poller.o

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=x64 libc= platform=freebsd)

SOLINK_MODULE(target) Release/obj.target/bindings.node

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=x64 libc= platform=freebsd)

COPY Release/bindings.node

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=x64 libc= platform=freebsd)

gmake: Leaving directory '/tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d/node_modules/@serialport/bindings/build'

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=x64 libc= platform=freebsd)

> core-js@3.15.0 postinstall /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d/node_modules/@babel/node/node_modules/core-js

> node -e "try{require('./postinstall')}catch(e){}"

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=x64 libc= platform=freebsd)

[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m

[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m

[96m>[94m https://opencollective.com/core-js [0m

[96m>[94m https://www.patreon.com/zloirock [0m

[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=x64 libc= platform=freebsd)

> core-js@2.6.12 postinstall /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d/node_modules/core-js

> node -e "try{require('./postinstall')}catch(e){}"

prebuild-install WARN install No prebuilt binaries found (target=14.17.0 runtime=node arch=x64 libc= platform=freebsd)

> core-js@2.6.12 postinstall /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d/node_modules/core-js

> node -e "try{require('./postinstall')}catch(e){}"

npm notice created a lockfile as package-lock.json. You should commit this file.

> core-js@2.6.12 postinstall /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d/node_modules/core-js

> node -e "try{require('./postinstall')}catch(e){}"

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})

> core-js@2.6.12 postinstall /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d/node_modules/core-js

> node -e "try{require('./postinstall')}catch(e){}"

> core-js@2.6.12 postinstall /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d/node_modules/core-js

> node -e "try{require('./postinstall')}catch(e){}"

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})

> core-js@2.6.12 postinstall /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d/node_modules/core-js

> node -e "try{require('./postinstall')}catch(e){}"

added 1407 packages from 741 contributors and audited 1956 packages in 45.985s

120 packages are looking for funding

run `npm fund` for details

found 9 vulnerabilities (2 moderate, 7 high)

run `npm audit fix` to fix them, or `npm audit` for details

> zwavejs2mqtt@5.0.4 build /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d

> npm-run-all build:*

> zwavejs2mqtt@5.0.4 build /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d

> npm-run-all build:*

sh: npm-run-all: not found

> zwavejs2mqtt@5.0.4 build /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d

> npm-run-all build:*

npm ERR! code ELIFECYCLE

> zwavejs2mqtt@5.0.4 build /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d

> npm-run-all build:*

npm ERR! syscall spawn

npm ERR! file sh

npm ERR! errno ENOENT

> zwavejs2mqtt@5.0.4 build /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d

> npm-run-all build:*

npm ERR! zwavejs2mqtt@5.0.4 build: `npm-run-all build:*`

> zwavejs2mqtt@5.0.4 build /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d

> npm-run-all build:*

npm ERR! spawn ENOENT

npm ERR!

npm ERR! Failed at the zwavejs2mqtt@5.0.4 build script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> zwavejs2mqtt@5.0.4 build /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d

> npm-run-all build:*

> zwavejs2mqtt@5.0.4 build /tmp/build_src.ccb8IJ2K/zwave-js-zwavejs2mqtt-51fa01d

> npm-run-all build:*

npm ERR! A complete log of this run can be found in:

npm ERR! /root/.npm/_logs/2021-06-20T20_39_42_738Z-debug.log

npm ERR! A complete log of this run can be found in:

npm ERR! /root/.npm/_logs/2021-06-20T20_39_42_738Z-debug.log

zwavejs2mqtt_enable: -> YES

npm ERR! A complete log of this run can be found in:

npm ERR! /root/.npm/_logs/2021-06-20T20_39_42_738Z-debug.log

Starting zwavejs2mqtt.

npm ERR! A complete log of this run can be found in:

npm ERR! /root/.npm/_logs/2021-06-20T20_39_42_738Z-debug.log

zwavejs2mqtt is not running.

npm ERR! A complete log of this run can be found in:

npm ERR! /root/.npm/_logs/2021-06-20T20_39_42_738Z-debug.log

Admin Portal:

http://192.168.178.42:8091

Doc URL:

https://github.com/tprelog/iocage-zwavejs2mqtt/wiki_

**Comment by tprelog** [comment]
Hi @RoelandvanD,

Thanks for reporting this -- I've pushed a quick update, can you either reinstall or run a Plugin UPDATE from the TrueNAS UI.

Let me know if this works.

Thanks again

**Comment by RoelandvanD** [comment]
Hi @tprelog 
I am very happy to report the update solved the issue. 
Thank you very much and keep up the good work!😎
