### ISSUE TITLE
8.5.0 fails to upgrade

### ISSUE THREAD

**Issue by MrRemmers** [tprelog/iocage-zwavejs2mqtt#2]
After upgrading homeassistant to 2021.10.0; z-wave integration complained it needed higher version so I tried to update the plugin.  after attempting an upgrade, the zw service would no longer start.

Being rather naïve in what I was doing; I found removing the options that presented error allowed the update to complete with warnings.  In "iocage-zwavejs2mqtt/overlay/root/bin/install_zj2m" line 28 and 29  unsafe-perm and --ignore-optional.

**Comment by tprelog** [comment]
I think this should do the trick
- https://github.com/tprelog/iocage-zwavejs2mqtt/commit/4d70121266466b6971f41b574dc065c247011c29
